# Generated by Django 2.2 on 2020-07-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
